# Generated by Django 5.2.6 on 2025-09-30 13:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizamiye', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='title',
        ),
        migrations.AddField(
            model_name='userdata',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='cikis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çıkış'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='giris',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giriş'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tckn',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='TCKN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='ziyaret',
            field=models.CharField(choices=[('YD', 'Yüksel DUMAN'), ('HS', 'Hayri ŞİMŞEK'), ('BK', 'Birgül KALKAN'), ('ET', 'Ercan TOKMAR'), ('GAI', 'Gönül AKIN İLHAN'), ('DEA', 'Durmuş Erdem ARSLANOĞLU'), ('AS', 'Atilla ŞAHİN'), ('GELIR', 'Gelir ve Kurumlar Vergileri Müdürlüğü'), ('KDV', 'KDV-ÖTV Müdürlüğü'), ('USUL', 'Usul Müdürlüğü'), ('TAH', 'Tahsilat Müdürlüğü'), ('DEN', 'Denetim Koordinasyon Müdürlüğü'), ('IHB', 'İhbar ve Şikayetleri Değerlendirme Müdürlüğü'), ('PERSO', 'Personel Müdürlüğü'), ('BILED', 'Bilgi Edinme Müdürlüğü'), ('IMIM', 'İdari ve Mali İşler Müdürlüğü'), ('BILIS', 'Bilgi İşlem ve Elektronik Belge Yönetim Müdürlüğü'), ('STRA', 'Strateji Müdürlüğü'), ('HUKUK', 'Hukuk Bürosu'), ('MUK', 'Mükellef Hizmetleri Müdürlüğü'), ('EGI', 'Eğitim Müdürlüğü'), ('AKVD', 'Ankara Kurumlar Vergi Dairesi'), ('YYVD', 'Yüzüncüyıl  Vergi Dairesi'), ('ANKVD', 'Ankara İhtisas Vergi Dairesi'), ('ANAVD', 'İhtisas Vergi Dairesi'), ('DOG', 'Doğanbey Vergi Dairesi'), ('YEN', 'Yenimahalle Vergi Dairesi'), ('TK1', '1. Nolu Takdir Komisyonu'), ('TK2', '2. Nolu Takdir Komisyonu'), ('TK3', '3. Nolu Takdir Komisyonu'), ('DIGER', 'Diğer')], default='DIGER', verbose_name='Geldiği Yer'),
            preserve_default=False,
        ),
    ]
