# Generated by Django 5.2.6 on 2025-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nizamiye', '0002_remove_userdata_content_remove_userdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='kart_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giriş Kart No:'),
        ),
    ]
